<template>
  <cl-crud ref="Crud"><cl-row><cl-refresh-btn /><cl-flex1 /><cl-search-key placeholder="搜索手机号或用户" /></cl-row><cl-row><cl-table ref="Table" /></cl-row><cl-row><cl-flex1 /><cl-pagination /></cl-row></cl-crud>
  <section v-if="visible" class="chat-workspace"><header class="chat-workspace__header"><el-button text @click="visible = false">返回会话列表</el-button><strong>客服会话</strong></header><AdvancedChat :current-user="staffUser" :chats="[chat]" :chat="chat" :messages="messages" :loading-messages="loading" :messages-loaded="true" :chats-loaded="true" :show-chats="false" :show-search="false" :show-add-chat="false" :show-files="false" :show-emojis="false" :show-reaction-emojis="false" :show-footer="true" :show-send-icon="true" height="calc(100vh - 100px)" theme="light" @send-message="sendMessage" /></section>
</template>
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'; import { ElMessage } from 'element-plus'; import { AdvancedChat, type ChatModel, type MessageModel, type User } from '@advanced-chat/components'; import '@advanced-chat/components/styles'; import { useCrud, useTable } from '@cool-vue/crud'; import { BaseService, useCool } from '/@/cool';
defineOptions({ name: 'loan-support' }); const { service } = useCool(); const loanServices = (service as any).loan || {}; const support = loanServices.support || new BaseService('/admin/loan/support'); const supportMessage = loanServices.supportMessage || new BaseService('/admin/loan/support-message'); const visible = ref(false); const loading = ref(false); const refreshing = ref(false); const currentId = ref<number>(); const staffUser: User = { id: 'staff', name: '客服', status: { state: 'online' } }; const customerUser: User = { id: 'customer', name: '用户', status: { state: 'online' } }; const messages = ref<MessageModel[]>([]); const chat = computed<ChatModel>(() => ({ id: String(currentId.value || 'support'), name: '客户会话', users: [staffUser, customerUser] }));
const mapMessage = (item: any): MessageModel => ({ id: String(item.id), sender: item.senderType === 'staff' ? staffUser : customerUser, content: item.content || undefined, createdAt: item.createTime || new Date().toISOString(), status: 'sent' });
const loadCurrentMessages = async (silent = false) => { if (!currentId.value || refreshing.value) return; refreshing.value = true; if (!silent) loading.value = true; try { const result = await supportMessage.request({ url: '/page', method: 'POST', data: { page: 1, size: 100, conversationId: currentId.value } }); const fetched = (result?.list || result?.data?.list || result?.data?.data?.list || []).map(mapMessage); if (fetched.length) { const merged = new Map(messages.value.map(item => [String(item.id), item])); fetched.forEach(item => merged.set(String(item.id), item)); messages.value = [...merged.values()].sort((a, b) => Number(a.id) - Number(b.id)); } } catch (error: any) { if (!silent) ElMessage.error(error?.message || '消息加载失败') } finally { refreshing.value = false; if (!silent) loading.value = false } };
const openChat = async (row: any) => { currentId.value = Number(row.id); visible.value = true; await loadCurrentMessages() };
const sendMessage = async (payload: { content: string }) => { if (!payload.content?.trim() || !currentId.value) return; try { const item = await support.request({ url: '/reply', method: 'POST', data: { conversationId: currentId.value, content: payload.content.trim() } }); messages.value.push(mapMessage(item)) } catch (error: any) { ElMessage.error(error?.message || '发送失败') } };
const copyLink = async (row: any) => { try { const result = await support.request({ url: '/access-token', method: 'POST', data: { conversationId: row.id } }); const origin = (import.meta.env.VITE_ADMIN_URL || window.location.origin).replace(/\/$/, ''); await navigator.clipboard.writeText(`${origin}/support/public?token=${encodeURIComponent(result.token)}`); ElMessage.success('免登录客服链接已复制') } catch (error: any) { ElMessage.error(error?.message || '生成链接失败') } };
const Table = useTable({ columns: [{ label: '用户', prop: 'userName', minWidth: 140 }, { label: '手机号', prop: 'phone', minWidth: 140 }, { label: '最后消息', prop: 'lastMessage', minWidth: 260, showOverflowTooltip: true }, { label: '未读', prop: 'staffUnread', width: 80 }, { label: '更新时间', prop: 'lastMessageAt', minWidth: 170 }, { type: 'op', width: 230, buttons: [{ label: '查看聊天', type: 'primary', onClick: ({ scope }: any) => openChat(scope.row) }, { label: '复制客服链接', onClick: ({ scope }: any) => copyLink(scope.row) }] }] }); const Crud = useCrud({ service: support }, app => app.refresh());
let refreshTimer: ReturnType<typeof setInterval> | undefined; onMounted(() => { refreshTimer = setInterval(() => { if (visible.value) loadCurrentMessages(true) }, 2000) }); onUnmounted(() => { if (refreshTimer) clearInterval(refreshTimer) });
</script>
<style scoped>.chat-workspace{position:fixed;inset:0;z-index:20;background:#fff}.chat-workspace__header{height:56px;display:flex;align-items:center;gap:18px;padding:0 18px;border-bottom:1px solid var(--el-border-color);background:#fff}.chat-workspace__header strong{font-size:16px}</style>
