<script setup lang="ts">
import { computed } from 'vue'
import AppTabbar from '../components/AppTabbar.vue'
import { money } from '../data/demo'
import { useLoanStore } from '../stores/loan'
const store=useLoanStore()
const review=computed(()=>({manual:{title:'人工审核中',desc:'专员正在核验您提交的申请材料',type:'warning'},phone:{title:'等待电话审核',desc:'请保持电话畅通，留意审核来电',type:'primary'},funding:{title:'市场配资中',desc:'正在匹配资金方案，可查看打款详情',type:'primary'},approved:{title:'审核已通过',desc:'请联系借款专员预约放款',type:'success'}}[store.reviewStage]))
</script>
<template><main class="page home"><header class="loan-hero"><div class="brand-row"><b><i>快</i> 快贷</b><router-link to="/messages"><van-icon name="bell" badge="2"/></router-link></div><p>最高可申请额度（元）</p><strong>{{money(300000)}}</strong><span>参考年化利率 7.2% 起，额度及利率以审核结果为准</span><van-button class="hero-apply-button" block round to="/auth">完善资料并申请</van-button></header><van-notice-bar wrapable left-icon="warning-o" color="#b42318" background="#fff1f0" text="快贷不收取任何放款前费用。凡以保证金、解冻费、刷流水等名义要求先付款的，均有诈骗风险。"/><section class="review-card"><div class="review-card__title"><div><span>借款进度</span><h2>{{review.title}}</h2></div><van-tag :type="review.type as any">处理中</van-tag></div><p>{{review.desc}}</p><van-steps :active="store.reviewStage==='manual'?0:store.reviewStage==='phone'?1:2"><van-step>人工审核</van-step><van-step>电话审核</van-step><van-step>配资放款</van-step></van-steps><van-button block plain round type="primary" to="/review-progress">查看进度详情</van-button></section><section class="feature-strip"><div><van-icon name="fire-o"/><b>快速评估</b><span>材料齐全后快速审核</span></div><div><van-icon name="shield-o"/><b>费用透明</b><span>不收取前期费用</span></div><div><van-icon name="calendar-o"/><b>灵活分期</b><span>支持多种期限方案</span></div></section><section class="section-head"><h2>申请资料</h2><router-link to="/auth">继续认证 <van-icon name="arrow"/></router-link></section><van-grid :column-num="4" :border="false"><van-grid-item icon="description-o" text="借条材料" to="/materials/iou"/><van-grid-item icon="balance-list-o" text="收入流水" to="/materials/income"/><van-grid-item icon="bill-o" text="负债信息" to="/materials/debt"/><van-grid-item class="customer-service-grid" icon="service-o" text="在线客服" to="/support"/></van-grid><section class="section-head home-loan-title"><h2>我的借款</h2><router-link to="/bills">查看账单 <van-icon name="arrow"/></router-link></section><section class="repay-card"><div class="repay-card__head"><span>下期应还</span><van-tag plain type="primary">还款中</van-tag></div><strong>{{money(1726.32)}}</strong><p>还款日 2026-10-11 · 剩余 4 期</p><van-button size="small" round type="primary" to="/repay/2026091101">立即还款</van-button></section><AppTabbar/></main></template>
