<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { showToast } from 'vant'
import { api, type LoanApplication } from '../api/client'
import { money } from '../data/demo'
import { getApplicationStatus, reviewStep } from '../utils/loan'
import PageNav from '../components/PageNav.vue'
const route=useRoute(),loading=ref(true),application=ref<LoanApplication|null>(null),showPlan=ref(false)
const status=computed(()=>getApplicationStatus(application.value?.status))
const monthly=computed(()=>{const app=application.value;if(!app)return 0;const p=Number(app.amount),n=Number(app.term),r=Number(app.annualRate||0)/1200;if(!r)return p/n;return p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)})
const totalInterest=computed(()=>monthly.value*Number(application.value?.term||0)-Number(application.value?.amount||0))
onMounted(async()=>{try{application.value=await api.applicationInfo(Number(route.params.id))}catch(error){showToast(error instanceof Error?error.message:'申请详情加载失败')}finally{loading.value=false}})
</script>
<template><main class="page bill-detail-page"><PageNav title="申请详情"/><van-loading v-if="loading" class="page-loading" vertical>加载中</van-loading><template v-else-if="application"><section class="bill-status" :class="application.status"><div><span>{{status.label}}</span><h1>{{money(Number(application.amount))}}</h1><p>{{status.description}}</p></div><van-icon :name="application.status==='approved'?'passed':application.status==='rejected'?'close':'clock-o'"/></section><section class="bill-metrics"><div><span>借款期限</span><b>{{application.term}} 期</b></div><div><span>年化利率</span><b>{{Number(application.annualRate||0)}}%</b></div><div><span>预计月还</span><b>{{money(monthly)}}</b></div></section><van-cell-group inset><van-cell title="申请编号" :value="application.applicationNo"/><van-cell title="借款用途" :value="application.purpose||'-'"/><van-cell title="收款银行" :value="application.bankName||'-'"/><van-cell title="提交时间" :value="application.submittedAt||'尚未提交'"/><van-cell title="预计总利息" :value="money(totalInterest)" is-link @click="showPlan=true"/></van-cell-group><section class="review-track"><h2>审批进度</h2><van-steps :active="reviewStep(application.status)" active-color="#2563eb"><van-step>资料审核</van-step><van-step>电话核验</van-step><van-step>放款审核</van-step><van-step>完成</van-step></van-steps><div v-if="application.reviewLogs?.length" class="review-events"><article v-for="item in [...application.reviewLogs].reverse()" :key="item.id"><i/><div><b>{{getApplicationStatus(item.toStatus).label}}</b><p>{{item.remark||'状态已更新'}}</p><time>{{item.createTime}}</time></div></article></div></section><van-cell-group inset><van-cell class="customer-service-cell" title="对此申请有疑问？" label="工作时间 09:30-19:30" value="咨询客服" icon="service-o" is-link to="/support"/></van-cell-group></template><van-empty v-else description="申请不存在"/><van-action-sheet v-model:show="showPlan" title="还款测算"><div class="repayment-estimate"><p>以下按等额本息方式测算，实际账单以审核通过后的放款结果为准。</p><van-cell title="每期预计还款" :value="money(monthly)"/><van-cell title="预计利息合计" :value="money(totalInterest)"/><van-cell title="预计还款合计" :value="money(monthly*Number(application?.term||0))"/></div></van-action-sheet></main></template>
